###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    database:
        image: mysql:5.7
        restart: always
        volumes:
            - ./phpdocker/mysql/script:/docker-entrypoint-initdb.d
        environment:
            TZ: Asia/Bangkok
            MYSQL_DATABASE: agriculture
            MYSQL_USER: agriculture
            MYSQL_PASSWORD: pp6321
            MYSQL_ROOT_PASSWORD: 123456
    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            TZ: Asia/Bangkok
            PMA_HOST: database
        ports:
            - 8001:80
        links: 
            - database

    webserver:
      image: nginx:alpine
      container_name: agriculture-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: agriculture-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

